### ISSUE TITLE
Failed to fetch lbry://gameoflife

### ISSUE THREAD

**Issue by lyoshenka** [loblao/lbry-slackbot#1]
I get the following error when I enter `lbry://gameoflife` into the chat

```
Traceback (most recent call last):
  File "bot.py", line 193, in <module>
    handle_url(url, channel)
  File "bot.py", line 155, in handle_url
    link = upload_to_imgur(filename, url)
  File "bot.py", line 91, in upload_to_imgur
    uploaded_image = im.upload_image(filename, title=url)
  File "/usr/local/lib/python2.7/dist-packages/pyimgur/__init__.py", line 1122, in upload_image
    with open(path, 'rb') as image_file:
IOError: [Errno 2] No such file or directory: u'files/gameoflife.gif'

```

Also, it would be nice if the bot printed more debugging info about what its trying to do , so it was easier to tell when its trying to do something and why it's failing.

**Comment by loblao** [comment]
Can `lbrynet-daemon` write to `files`? I have added some debug messages in 8b53f7e75418f466a3589059fcb96d7c14ea4554

**Comment by lyoshenka** [comment]
It still says 

```
WARNING: files/gameoflife.gif not found!
WARNING: Check if you have write access to files
```

even though files is world-writable. 

This made it work for me:

```
-OUTPUT_DIR = CONFIG.get('OUTPUT_DIR', 'files')
+OUTPUT_DIR = os.path.abspath(CONFIG.get('OUTPUT_DIR', 'files'))
```
